
CREATE TABLE IF NOT EXISTS `pictures` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `desc` text NOT NULL,
  `level` int(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;



INSERT INTO `pictures` (`id`, `title`, `name`, `desc`, `level`) VALUES
(1, 'System of a Down', 'soad.jpg', 'They Still the best innit ?', 1),
(2, 'Anime Girl', 'anime.jpg', 'it''s obvious what she wants', 1),
(3, 'I''ve Lost my JOB', 'job.jpg', 'I just lost my job', 1),
(4, 'Nexus', 'nexus.jpg', 'The H00ly New Nexus', 1),
(5, 'Droid', 'droid.jpg', 'this green droid looks like c16 if you know what i mean', 1),
(6, 'haKKur', 'hakkur.jpg', 'this aint no hakkur this is a nerdy ass', 1),
(7, 'Math Dewd', 'real.jpg', 'that one guy who has to correct the professor on everything, math-related or not', 1),
(8, 'Mariaaa', 'maria.jpg', 'What are the long-term effects of marijauna on your brain? \nBasically...will it make you dumb...?\nwell fuck you !!!\nit''s pure magic fella', 1),
(9, 'flag', 'flag.jpg', 'you have finally found meh ! good job :)', 2);


CREATE TABLE IF NOT EXISTS `users` (
  `id_user` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `level` int(5) NOT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=203 ;

INSERT INTO `users` (`id_user`, `username`, `password`, `level`) VALUES
(3, 'boxercheek', 'masked for security reason', 0),
(4, 'mechanicmandrill', 'masked for security reason', 0),
(5, 'determinedpositive', 'masked for security reason', 0),
(6, 'variableminecart', 'masked for security reason', 0),
(7, 'poncyborn', 'masked for security reason', 0),
(8, 'grotesquetaking', 'masked for security reason', 0),
(9, 'clearedvictor', 'masked for security reason', 0),
(10, 'facedgrease', 'masked for security reason', 0),
(11, 'georgianclot', 'masked for security reason', 0),
(12, 'soullesschatter', 'masked for security reason', 0),
(13, 'oatmealtoboggan', 'masked for security reason', 0),
(14, 'tenuntidy', 'masked for security reason', 0),
(15, 'haggischeshire', 'masked for security reason', 0),
(16, 'pedunclecoati', 'masked for security reason', 0),
(17, 'crummydingdong', 'masked for security reason', 0),
(18, 'snotcurrish', 'masked for security reason', 0),
(19, 'awesomegrateful', 'masked for security reason', 0),
(20, 'contentflock', 'masked for security reason', 0),
(21, 'spoonpillock', 'masked for security reason', 0),
(22, 'primewaste', 'masked for security reason', 0),
(23, 'maturewideeyed', 'masked for security reason', 0),
(24, 'puppiesevery', 'masked for security reason', 0),
(25, 'attemptpizzle', 'masked for security reason', 0),
(26, 'steadfastensorcell', 'masked for security reason', 0),
(27, 'turtledovevibrant', 'masked for security reason', 0),
(28, 'unfoldedclunk', 'masked for security reason', 0),
(29, 'longtermpaltry', 'masked for security reason', 0),
(30, 'thunderousnesting', 'masked for security reason', 0),
(31, 'criticizemoulting', 'masked for security reason', 0),
(32, 'injurebellowing', 'masked for security reason', 0),
(33, 'pecantelephone', 'masked for security reason', 0),
(34, 'telephonepains', 'masked for security reason', 0),
(35, 'bureaucratbobble', 'masked for security reason', 0),
(36, 'indianusurp', 'masked for security reason', 0),
(37, 'matdoading', 'masked for security reason', 0),
(38, 'hickgalled', 'masked for security reason', 0),
(39, 'femurplonk', 'masked for security reason', 0),
(40, 'coatipools', 'masked for security reason', 0),
(41, 'glozingfurnace', 'masked for security reason', 0),
(42, 'irisverdant', 'masked for security reason', 0),
(43, 'dreamingcollective', 'masked for security reason', 0),
(44, 'stakingproperty', 'masked for security reason', 0),
(45, 'bolthumor', 'masked for security reason', 0),
(46, 'paramedicflagella', 'masked for security reason', 0),
(47, 'fortunatebudget', 'masked for security reason', 0),
(48, 'raftingweaver', 'masked for security reason', 0),
(49, 'quizzicalbrand', 'masked for security reason', 0),
(50, 'bloatnote', 'masked for security reason', 0),
(51, 'skincountless', 'masked for security reason', 0),
(52, 'cherriesparkour', 'masked for security reason', 0),
(53, 'hockeysnap', 'masked for security reason', 0),
(54, 'cagedagitated', 'masked for security reason', 0),
(55, 'asklacrosse', 'masked for security reason', 0),
(56, 'therapistknock', 'masked for security reason', 0),
(57, 'littleskinny', 'masked for security reason', 0),
(58, 'uselessintroduce', 'masked for security reason', 0),
(59, 'racialmallet', 'masked for security reason', 0),
(60, 'salamitaekwondo', 'masked for security reason', 0),
(61, 'victoriousspoon', 'masked for security reason', 0),
(62, 'tightacoustic', 'masked for security reason', 0),
(63, 'gildhandlers', 'masked for security reason', 0),
(64, 'halftimedentist', 'masked for security reason', 0),
(65, 'racinghappy', 'masked for security reason', 0),
(66, 'traingrind', 'masked for security reason', 0),
(67, 'dummysticker', 'masked for security reason', 0),
(68, 'abandonedworthless', 'masked for security reason', 0),
(69, 'carvecreepy', 'masked for security reason', 0),
(70, 'sardineslibyan', 'masked for security reason', 0),
(71, 'momentouscynical', 'masked for security reason', 0),
(72, 'correctsecondhand', 'masked for security reason', 0),
(73, 'bangershay', 'masked for security reason', 0),
(74, 'sowphew', 'masked for security reason', 0),
(75, 'negativeallow', 'masked for security reason', 0),
(76, 'waitjumpy', 'masked for security reason', 0),
(77, 'unnaturalrumbling', 'masked for security reason', 0),
(78, 'keycandid', 'masked for security reason', 0),
(79, 'speakpainted', 'masked for security reason', 0),
(80, 'hairyblackberry', 'masked for security reason', 0),
(81, 'easyshameless', 'masked for security reason', 0),
(82, 'dimpledfrigid', 'masked for security reason', 0),
(83, 'writesick', 'masked for security reason', 0),
(84, 'donnybrooktempt', 'masked for security reason', 0),
(85, 'pridetrounce', 'masked for security reason', 0),
(86, 'proficientubiquity', 'masked for security reason', 0),
(87, 'iglooturd', 'masked for security reason', 0),
(88, 'eyrarcows', 'masked for security reason', 0),
(89, 'hidesled', 'masked for security reason', 0),
(90, 'bladderincredible', 'masked for security reason', 0),
(91, 'eliteunicycle', 'masked for security reason', 0),
(92, 'chimpkids', 'masked for security reason', 0),
(93, 'fatuouswomb', 'masked for security reason', 0),
(94, 'distressedfire', 'masked for security reason', 0),
(95, 'chopsshrewdness', 'masked for security reason', 0),
(96, 'avocetcurved', 'masked for security reason', 0),
(97, 'deltoidsuggest', 'masked for security reason', 0),
(98, 'detailedshabby', 'masked for security reason', 0),
(99, 'wallowblooded', 'masked for security reason', 0),
(100, 'theorizeroast', 'masked for security reason', 0),
(101, 'soupaloof', 'masked for security reason', 0),
(102, 'agreeableyorkshire', 'masked for security reason', 0),
(103, 'chickensport', 'masked for security reason', 0),
(104, 'falconsurmise', 'masked for security reason', 0),
(105, 'toolcoalore', 'masked for security reason', 0),
(106, 'liartimid', 'masked for security reason', 0),
(107, 'pantswriggle', 'masked for security reason', 0),
(108, 'savageryexcellent', 'masked for security reason', 0),
(109, 'ratsbanebladder', 'masked for security reason', 0),
(110, 'trenchforetell', 'masked for security reason', 0),
(111, 'parrotmonkey', 'masked for security reason', 0),
(112, 'witcheswashing', 'masked for security reason', 0),
(113, 'sinreasonable', 'masked for security reason', 0),
(114, 'beamchiming', 'masked for security reason', 0),
(115, 'puddingschinese', 'masked for security reason', 0),
(116, 'shapelesstroubled', 'masked for security reason', 0),
(117, 'direfulresolute', 'masked for security reason', 0),
(118, 'hogwashcrag', 'masked for security reason', 0),
(119, 'showymushroom', 'masked for security reason', 0),
(120, 'whirrsowse', 'masked for security reason', 0),
(121, 'pepperbuy', 'masked for security reason', 0),
(122, 'wolfbesiege', 'masked for security reason', 0),
(123, 'healthysmacked', 'masked for security reason', 0),
(124, 'grandurethra', 'masked for security reason', 0),
(125, 'heatingopen', 'masked for security reason', 0),
(126, 'stitchedmoral', 'masked for security reason', 0),
(127, 'dictat0R', 'masked for security reason', 0),
(128, 'celebratedwoodcock', 'masked for security reason', 0),
(129, 'murmurvalid', 'masked for security reason', 0),
(130, 'puzzlingcroak', 'masked for security reason', 0),
(131, 'noisyjohns', 'masked for security reason', 0),
(132, 'possibleshout', 'masked for security reason', 0),
(133, 'canoeyeasty', 'masked for security reason', 0),
(134, 'walktrip', 'masked for security reason', 0),
(135, 'smuthpant', 'masked for security reason', 0),
(136, 'recallgoggles', 'masked for security reason', 0),
(137, 'otherdowdy', 'masked for security reason', 0),
(138, 'paternaldelightful', 'masked for security reason', 0),
(139, 'diffidencecourageous', 'masked for security reason', 0),
(140, 'cackledoodle', 'masked for security reason', 0),
(141, 'rosaryresentful', 'masked for security reason', 0),
(142, 'barterrider', 'masked for security reason', 0),
(143, 'flumetie', 'masked for security reason', 0),
(144, 'redneckremarkable', 'masked for security reason', 0),
(145, 'listmews', 'masked for security reason', 0),
(146, 'duckbleed', 'masked for security reason', 0),
(147, 'limbbossy', 'masked for security reason', 0),
(148, 'dragonplop', 'masked for security reason', 0),
(149, 'ovarymaniacal', 'masked for security reason', 0),
(150, 'kitchenherb', 'masked for security reason', 0),
(151, 'sparklingbass', 'masked for security reason', 0),
(152, 'murderousjoyful', 'masked for security reason', 0),
(153, 'whoppingrug', 'masked for security reason', 0),
(154, 'joinedhartebeest', 'masked for security reason', 0),
(155, 'offbeatpear', 'masked for security reason', 0),
(156, 'bugsinnocent', 'masked for security reason', 0),
(157, 'gulliblerequired', 'masked for security reason', 0),
(158, 'raspcrusty', 'masked for security reason', 0),
(159, 'stretchbale', 'masked for security reason', 0),
(160, 'joghopeful', 'masked for security reason', 0),
(161, 'blubbershooter', 'masked for security reason', 0),
(162, 'jellyfishblast', 'masked for security reason', 0),
(163, 'obnoxioushive', 'masked for security reason', 0),
(164, 'turkeyfar', 'masked for security reason', 0),
(165, 'panjandrumwait', 'masked for security reason', 0),
(166, 'unhealthyquail', 'masked for security reason', 0),
(167, 'skeletonsparkle', 'masked for security reason', 0),
(168, 'dovesugliest', 'masked for security reason', 0),
(169, 'auroracream', 'masked for security reason', 0),
(170, 'reflectprawns', 'masked for security reason', 0),
(171, 'makedive', 'masked for security reason', 0),
(172, 'sugarcanehorse', 'masked for security reason', 0),
(173, 'friedoriginal', 'masked for security reason', 0),
(174, 'secretarybrakes', 'masked for security reason', 0),
(175, 'gritbroad', 'masked for security reason', 0),
(176, 'transportibexe', 'masked for security reason', 0),
(177, 'crashingbread', 'masked for security reason', 0),
(178, 'magpiehusk', 'masked for security reason', 0),
(179, 'madclack', 'masked for security reason', 0),
(180, 'flapjacksblurt', 'masked for security reason', 0),
(181, 'twanghometeam', 'masked for security reason', 0),
(182, 'ragethy', 'masked for security reason', 0),
(183, 'cheekygazebo', 'masked for security reason', 0),
(184, 'cowboysbuild', 'masked for security reason', 0),
(185, 'turnipaxel', 'masked for security reason', 0),
(186, 'cleaningtnt', 'masked for security reason', 0),
(187, 'deathclocks', 'masked for security reason', 0),
(188, 'conspiracyowl', 'masked for security reason', 0),
(189, 'triangularpeafowl', 'masked for security reason', 0),
(190, 'clankingvivid', 'masked for security reason', 0),
(191, 'ludicrousslang', 'masked for security reason', 0),
(192, 'reelinghunt', 'masked for security reason', 0),
(193, 'saybundle', 'masked for security reason', 0),
(194, 'mercifulsurly', 'masked for security reason', 0),
(195, 'trimminghick', 'masked for security reason', 0),
(196, 'divernew', 'masked for security reason', 0),
(197, 'stircandidate', 'masked for security reason', 0),
(198, 'glisteningmango', 'masked for security reason', 0),
(199, 'ptarmiganswitch', 'masked for security reason', 0),
(200, 'pedlarmodern', 'masked for security reason', 0),
(201, 'baublebroth', 'masked for security reason', 0),
(202, 'jackthefarmer', 'masked for security reason', 0);